---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	entity_extract(entity_extract)
	column_retrieval_node(column_retrieval_node)
	metrics_retrieval_node(metrics_retrieval_node)
	value_retrieval_node(value_retrieval_node)
	merge_node(merge_node)
	table_filter_node(table_filter_node)
	metric_filter_node(metric_filter_node)
	expand_node(expand_node)
	generate_hql_node(generate_hql_node)
	validate_hql_node(validate_hql_node)
	missing_complete_node(missing_complete_node)
	correct_hql_node(correct_hql_node)
	execute_hql_node(execute_hql_node)
	fallback_node(fallback_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> entity_extract;
	column_retrieval_node --> merge_node;
	correct_hql_node --> validate_hql_node;
	entity_extract --> column_retrieval_node;
	entity_extract --> metrics_retrieval_node;
	entity_extract --> value_retrieval_node;
	expand_node --> generate_hql_node;
	generate_hql_node --> validate_hql_node;
	merge_node --> metric_filter_node;
	merge_node --> table_filter_node;
	metric_filter_node --> expand_node;
	metrics_retrieval_node --> merge_node;
	missing_complete_node -. &nbsp;fallback&nbsp; .-> fallback_node;
	missing_complete_node -. &nbsp;correct_hql&nbsp; .-> correct_hql_node;
	table_filter_node --> expand_node;
	validate_hql_node -. &nbsp;execute_hql&nbsp; .-> execute_hql_node;
	validate_hql_node -. &nbsp;fallback&nbsp; .-> fallback_node;
	validate_hql_node -. &nbsp;missing_complete&nbsp; .-> missing_complete_node;
	value_retrieval_node --> merge_node;
	execute_hql_node --> __end__;
	fallback_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc